manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson/zmk
      url-base: https://github.com/petejohanson/zmk
  projects:
    - name: zmk
      remote: petejohanson/zmk
      revision: feat/pointers-move-scroll
      import: app/west.yml
  self:
    path: config
