manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: pointers-move-scroll
      url-base: https://github.com/petejohanson/zmk.git
  projects:
    - name: zmk
      remote: pointers-move-scroll
      revision: pointers-move-scroll
      import: app/west.yml
  self:
    path: config
