manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: pointers-move
      url-base: https://github.com/petejohanson/zmk
  projects:
    - name: pointers-move
      remote: zmk
      revision: main
      import: app/west.yml
  self:
    path: config
